In [2]:
import pandas as pd
import numpy as np
import glob
import os

In [5]:
all_times_df = pd.read_csv("../../Datasets/archived_feeds.txt")
all_times_df = all_times_df.drop(['archive_note'], axis=1)
all_times_df['feed_start_date'] = pd.to_datetime(all_times_df['feed_start_date'], format='%Y%m%d')
all_times_df['feed_end_date'] = pd.to_datetime(all_times_df['feed_end_date'], format='%Y%m%d')
all_times_df

,feed_start_date,feed_end_date,feed_version,archive_url
0,2026-03-28,2026-06-13,"Spring 2026, 2026-04-04T23:34:29+00:00, version D",https://cdn.mbtace.com/archive/20260328.zip
1,2026-03-27,2026-03-27,"Spring 2026, 2026-04-03T18:45:06+00:00, version D",https://cdn.mbtace.com/archive/20260327.zip
2,2026-03-23,2026-03-26,"Spring 2026, 2026-03-30T21:02:11+00:00, version D",https://cdn.mbtace.com/archive/20260323.zip
3,2026-03-20,2026-03-22,"Spring 2026, 2026-03-27T18:55:10+00:00, version D",https://cdn.mbtace.com/archive/20260320.zip
4,2026-03-19,2026-03-19,"Spring 2026, 2026-03-26T22:58:34+00:00, version D",https://cdn.mbtace.com/archive/20260319.zip
...,...,...,...,...
948,2009-05-15,2009-05-28,"GTFS file for Google Transit, published 5/15/09",https://cdn.mbtace.com/archive/20090515.zip
949,2009-04-24,2009-05-14,"GTFS file for Google Transit, published 4/24/09",https://cdn.mbtace.com/archive/20090424.zip
950,2009-04-09,2009-04-23,"GTFS file for Google Transit, published 4/9/09",https://cdn.mbtace.com/archive/20090409.zip
951,2009-04-03,2009-04-08,"GTFS file for Google Transit, published 4/3/09",https://cdn.mbtace.com/archive/20090403.zip
952,2009-03-13,2009-04-02,"GTFS file for Google Transit, published 3/13/09",https://cdn.mbtace.com/archive/20090313.zip

In [ ]:
# obtain all final events data for 2022-2026
df_list = []
for i in range(2, 6):
    dir = glob.glob(f'/Users/sierrawelsch/CS4100_Final/Datasets/202{i}/*.csv')
    for month_csv_file in dir:
        month_csv_file_df = pd.read_csv(month_csv_file)
        
        df_list.append(month_csv_file_df)
print(len(df_list))
final_events_df = pd.concat(df_list, ignore_index=True)
final_events_df

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/2496437002.py:5: DtypeWarning: Columns (0: vehicle_label) have mixed types. Specify dtype option on import or set low_memory=False.
  month_csv_file_df = pd.read_csv(month_csv_file)

48

,service_date,route_id,trip_id,direction_id,stop_id,stop_sequence,vehicle_id,vehicle_label,event_type,event_time,event_time_sec,trunk_route_id,direction,parent_station,stop_name,sync_stop_sequence
0,2022-07-01,Red,52370898,0,70061,1.0,R-547147BD,1882.0,ARR,1656736332,88332.0,NaN,NaN,NaN,NaN,NaN
1,2022-07-01,Red,52370898,0,70061,1.0,R-547147BD,1860.0,DEP,1656736536,88536.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-01,Red,52370898,0,70063,10.0,R-547147BD,1860.0,ARR,1656736791,88791.0,NaN,NaN,NaN,NaN,NaN
3,2022-07-01,Red,52370898,0,70063,10.0,R-547147BD,1860.0,DEP,1656736833,88833.0,NaN,NaN,NaN,NaN,NaN
4,2022-07-01,Red,52370898,0,70065,20.0,R-547147BD,1860.0,ARR,1656736903,88903.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38060958,2025-11-29,Red,NONREV-1580718040,1,70092,NaN,R-5486BE8E,1516,DEP,2025-11-29T05:43:36Z,20616.0,Red,North,place-smmnl,Shawmut,3.0
38060959,2025-11-29,Red,71070775,1,70072,NaN,R-5486BE8E,1516,DEP,2025-11-29T07:40:45Z,27645.0,Red,North,place-knncl,Kendall/MIT,13.0
38060960,2025-11-29,Red,71070826,1,70078,NaN,R-5486BE99,1940,DEP,2025-11-29T18:31:16Z,66676.0,Red,North,place-dwnxg,Downtown Crossing,10.0
38060961,2025-11-29,Red,71070821,1,70094,NaN,R-5486BFF3,1752,DEP,2025-11-29T17:15:37Z,62137.0,Red,North,place-asmnl,Ashmont,2.0
38060962,2025-11-29,Red,NONREV-1580718102,1,70066,NaN,R-5486C079,1751,DEP,2025-11-29T15:11:00Z,54660.0,Red,North,place-portr,Porter,16.0

In [ ]:
new_final_events_df = final_events_df.drop(["vehicle_id", "vehicle_label", "direction_id", "parent_station", "trunk_route_id", "direction", "stop_name"], axis = 1)
new_final_events_df['stop_sequence_id'] = new_final_events_df['stop_sequence'].combine_first(new_final_events_df['sync_stop_sequence'])
new_final_events_df = new_final_events_df.drop(['sync_stop_sequence', 'stop_sequence'], axis=1)
new_final_events_df = new_final_events_df.dropna()

new_final_events_df

,service_date,route_id,trip_id,stop_id,event_type,event_time,event_time_sec,stop_sequence_id
0,2022-07-01,Red,52370898,70061,ARR,1656736332,88332.0,1.0
1,2022-07-01,Red,52370898,70061,DEP,1656736536,88536.0,1.0
2,2022-07-01,Red,52370898,70063,ARR,1656736791,88791.0,10.0
3,2022-07-01,Red,52370898,70063,DEP,1656736833,88833.0,10.0
4,2022-07-01,Red,52370898,70065,ARR,1656736903,88903.0,20.0
...,...,...,...,...,...,...,...,...
38060958,2025-11-29,Red,NONREV-1580718040,70092,DEP,2025-11-29T05:43:36Z,20616.0,3.0
38060959,2025-11-29,Red,71070775,70072,DEP,2025-11-29T07:40:45Z,27645.0,13.0
38060960,2025-11-29,Red,71070826,70078,DEP,2025-11-29T18:31:16Z,66676.0,10.0
38060961,2025-11-29,Red,71070821,70094,DEP,2025-11-29T17:15:37Z,62137.0,2.0
38060962,2025-11-29,Red,NONREV-1580718102,70066,DEP,2025-11-29T15:11:00Z,54660.0,16.0

In [ ]:
# merging the tables to map each stop times zip file to the appropriate event based on the event date (service_date)
new_final_events_df['service_date'] = pd.to_datetime(new_final_events_df['service_date']).astype('datetime64[ns]')
all_times_df['feed_start_date'] = pd.to_datetime(all_times_df['feed_start_date']).astype('datetime64[ns]')

new_final_events_df = new_final_events_df.sort_values('service_date')
all_times_df = all_times_df.sort_values('feed_start_date')

merged = pd.merge_asof(
    new_final_events_df,
    all_times_df,
    left_on='service_date',
    right_on='feed_start_date',
    direction='backward'
)
merged = merged.sort_values('service_date')
merged

,service_date,route_id,trip_id,stop_id,event_type,event_time,event_time_sec,stop_sequence_id,feed_start_date,feed_end_date,feed_version,archive_url
0,2022-01-01,Orange,50346799,70007,ARR,1641090593,77393.0,30.0,2021-12-31,2022-01-02,"Winter 2022, 2022-01-07T21:27:20+00:00, version D",https://cdn.mbtace.com/archive/20211231.zip
14723,2022-01-01,Red,50346247,70096,ARR,1641046053,32853.0,100.0,2021-12-31,2022-01-02,"Winter 2022, 2022-01-07T21:27:20+00:00, version D",https://cdn.mbtace.com/archive/20211231.zip
14722,2022-01-01,Red,50346247,70096,DEP,1641046121,32921.0,100.0,2021-12-31,2022-01-02,"Winter 2022, 2022-01-07T21:27:20+00:00, version D",https://cdn.mbtace.com/archive/20211231.zip
14721,2022-01-01,Red,50346247,70098,DEP,1641045685,32485.0,40.0,2021-12-31,2022-01-02,"Winter 2022, 2022-01-07T21:27:20+00:00, version D",https://cdn.mbtace.com/archive/20211231.zip
14720,2022-01-01,Red,50346247,70082,ARR,1641046346,33146.0,120.0,2021-12-31,2022-01-02,"Winter 2022, 2022-01-07T21:27:20+00:00, version D",https://cdn.mbtace.com/archive/20211231.zip
...,...,...,...,...,...,...,...,...,...,...,...,...
37919154,2025-12-31,Red,ADDED-1583428392,70084,DEP,2025-12-31T22:19:33Z,80373.0,7.0,2025-12-31,2025-12-31,"Winter 2026, 2026-01-07T19:45:12+00:00, version D",https://cdn.mbtace.com/archive/20251231.zip
37919155,2025-12-31,Red,ADDED-1583426536,70070,DEP,2025-12-31T16:09:19Z,58159.0,14.0,2025-12-31,2025-12-31,"Winter 2026, 2026-01-07T19:45:12+00:00, version D",https://cdn.mbtace.com/archive/20251231.zip
37919156,2025-12-31,Red,74031390,70086,DEP,2025-12-31T17:26:27Z,62787.0,6.0,2025-12-31,2025-12-31,"Winter 2026, 2026-01-07T19:45:12+00:00, version D",https://cdn.mbtace.com/archive/20251231.zip
37919149,2025-12-31,Red,74031553,70076,DEP,2025-12-31T11:36:36Z,41796.0,11.0,2025-12-31,2025-12-31,"Winter 2026, 2026-01-07T19:45:12+00:00, version D",https://cdn.mbtace.com/archive/20251231.zip
37945353,2025-12-31,Red,74031568,70096,ARR,2025-12-31T14:18:44Z,51524.0,6.0,2025-12-31,2025-12-31,"Winter 2026, 2026-01-07T19:45:12+00:00, version D",https://cdn.mbtace.com/archive/20251231.zip

In [ ]:
import os
import requests
import zipfile

os.makedirs("stop_times", exist_ok=True)
os.makedirs("zips", exist_ok=True)

# Keep track of currently downloaded ZIPs
downloaded_zips = {}  # url -> local path

def download_zip(url):
    filename = url.split("/")[-1]
    path = os.path.join("zips", filename)
    
    if url not in downloaded_zips:
        if not os.path.exists(path):
            print(f"Downloading {filename}")
            r = requests.get(url)
            with open(path, "wb") as f:
                f.write(r.content)
        downloaded_zips[url] = path
    return downloaded_zips[url]

def extract_stop_times(zip_path):
    filename = zip_path.split("/")[-1].replace(".zip", ".txt")
    output_path = os.path.join("stop_times", filename)
    
    if not os.path.exists(output_path):
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extract("stop_times.txt", "temp_extract")
            os.rename("temp_extract/stop_times.txt", output_path)
            os.rmdir("temp_extract")
    return output_path

def clean_old_zips(zip_path):
    """Delete ZIPs not in the active set."""
    os.remove(f'src/preprocessing/{zip_path}')
    print(f"Deleted old ZIP: {zip_path}")

In [ ]:
# download a stops_times.txt file per month per years defined ()
stop_times_map = {}
unique_urls = merged['archive_url'].dropna().unique()
last_downloaded = "20240402.zip"
target_month = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
target_year = ["2022", "2023", "2024", "2025"]

midx = 0
yidx = 0
for url in unique_urls:
    date = url.split("/")[-1].replace(".zip", "")
    year = date[:4]
    month = date[4:6]
    day = date[6:]
    print(year, month, day)
    print(date)
    if target_month[midx] in month and target_year[yidx] in year:
        zip_path = download_zip(url)
        
        stop_times_path = extract_stop_times(zip_path)
        clean_old_zips(zip_path)
        if yidx == 3 and midx == 11:
            break
        elif midx == 11:
            yidx += 1
            midx = 0
        else:
            midx += 1

2021 12 31
20211231
2022 01 03
20220103
{'in!'}
Downloading 20220103.zip
Deleted old ZIP: zips/20220103.zip
2022 01 06
20220106
2022 01 13
20220113
2022 01 20
20220120
2022 01 21
20220121
2022 01 27
20220127
2022 02 04
20220204
{'in!'}
Downloading 20220204.zip
Deleted old ZIP: zips/20220204.zip
2022 02 15
20220215
2022 02 17
20220217
2022 02 23
20220223
2022 02 28
20220228
2022 03 02
20220302
{'in!'}
Downloading 20220302.zip
Deleted old ZIP: zips/20220302.zip
2022 03 03
20220303
2022 03 04
20220304
2022 03 09
20220309
2022 03 10
20220310
2022 03 12
20220312
2022 03 14
20220314
2022 03 17
20220317
2022 03 21
20220321
2022 03 22
20220322
2022 03 23
20220323
2022 03 25
20220325
2022 03 30
20220330
2022 04 02
20220402
{'in!'}
Downloading 20220402.zip
Deleted old ZIP: zips/20220402.zip
2022 04 04
20220404
2022 04 05
20220405
2022 04 08
20220408
2022 04 19
20220419
2022 04 21
20220421
2022 04 22
20220422
2022 04 26
20220426
2022 04 30
20220430
2022 05 01
20220501
{'in!'}
Downloading 20220501.zip
Deleted old ZIP: zips/20220501.zip
2022 05 02
20220502
2022 05 05
20220505
2022 05 06
20220506
2022 05 11
20220511
2022 05 13
20220513
2022 05 24
20220524
2022 05 26
20220526
2022 05 27
20220527
2022 05 31
20220531
2022 06 02
20220602
{'in!'}
Downloading 20220602.zip
Deleted old ZIP: zips/20220602.zip
2022 06 03
20220603
2022 06 09
20220609
2022 06 10
20220610
2022 06 16
20220616
2022 06 23
20220623
2022 06 30
20220630
2022 07 01
20220701
{'in!'}
Downloading 20220701.zip
Deleted old ZIP: zips/20220701.zip
2022 07 06
20220706
2022 07 12
20220712
2022 07 19
20220719
2022 07 20
20220720
2022 07 22
20220722
2022 07 27
20220727
2022 08 03
20220803
{'in!'}
Downloading 20220803.zip
Deleted old ZIP: zips/20220803.zip
2022 08 08
20220808
2022 08 09
20220809
2022 08 10
20220810
2022 08 11
20220811
2022 08 12
20220812
2022 08 16
20220816
2022 08 17
20220817
2022 08 23
20220823
2022 08 25
20220825
2022 08 26
20220826
2022 09 01
20220901
{'in!'}
Downloading 20220901.zip
Deleted old ZIP: zips/20220901.zip
2022 09 05
20220905
2022 09 06
20220906
2022 09 08
20220908
2022 09 13
20220913
2022 09 14
20220914
2022 09 16
20220916
2022 09 22
20220922
2022 09 23
20220923
2022 09 29
20220929
2022 10 05
20221005
{'in!'}
Downloading 20221005.zip
Deleted old ZIP: zips/20221005.zip
2022 10 07
20221007
2022 10 11
20221011
2022 10 13
20221013
2022 10 19
20221019
2022 10 20
20221020
2022 10 21
20221021
2022 10 28
20221028
2022 10 29
20221029
2022 11 04
20221104
{'in!'}
Downloading 20221104.zip
Deleted old ZIP: zips/20221104.zip
2022 11 09
20221109
2022 11 14
20221114
2022 11 21
20221121
2022 11 23
20221123
2022 11 24
20221124
2022 11 28
20221128
2022 12 01
20221201
{'in!'}
Downloading 20221201.zip
Deleted old ZIP: zips/20221201.zip
2022 12 06
20221206
2022 12 09
20221209
2022 12 13
20221213
2022 12 15
20221215
2022 12 22
20221222
2022 12 29
20221229
2023 01 04
20230104
{'in!'}
Downloading 20230104.zip
Deleted old ZIP: zips/20230104.zip
2023 01 17
20230117
2023 01 24
20230124
2023 01 25
20230125
2023 01 27
20230127
2023 01 28
20230128
2023 01 30
20230130
2023 01 31
20230131
2023 02 02
20230202
{'in!'}
Downloading 20230202.zip
Deleted old ZIP: zips/20230202.zip
2023 02 03
20230203
2023 02 16
20230216
2023 02 21
20230221
2023 02 24
20230224
2023 02 27
20230227
2023 03 02
20230302
{'in!'}
Downloading 20230302.zip
Deleted old ZIP: zips/20230302.zip
2023 03 03
20230303
2023 03 06
20230306
2023 03 10
20230310
2023 03 12
20230312
2023 03 16
20230316
2023 03 20
20230320
2023 03 22
20230322
2023 03 24
20230324
2023 03 27
20230327
2023 03 29
20230329
2023 04 01
20230401
{'in!'}
Downloading 20230401.zip
Deleted old ZIP: zips/20230401.zip
2023 04 04
20230404
2023 04 05
20230405
2023 04 06
20230406
2023 04 08
20230408
2023 04 09
20230409
2023 04 12
20230412
2023 04 14
20230414
2023 04 17
20230417
2023 04 25
20230425
2023 04 28
20230428
2023 05 04
20230504
{'in!'}
Downloading 20230504.zip
Deleted old ZIP: zips/20230504.zip
2023 05 05
20230505
2023 05 10
20230510
2023 05 12
20230512
2023 05 19
20230519
2023 05 23
20230523
2023 05 25
20230525
2023 05 26
20230526
2023 05 30
20230530
2023 06 02
20230602
{'in!'}
Downloading 20230602.zip
Deleted old ZIP: zips/20230602.zip
2023 06 07
20230607
2023 06 09
20230609
2023 06 14
20230614
2023 06 19
20230619
2023 06 20
20230620
2023 06 22
20230622
2023 06 23
20230623
2023 06 27
20230627
2023 06 29
20230629
2023 07 01
20230701
{'in!'}
Downloading 20230701.zip
Deleted old ZIP: zips/20230701.zip
2023 07 03
20230703
2023 07 05
20230705
2023 07 07
20230707
2023 07 12
20230712
2023 07 13
20230713
2023 07 21
20230721
2023 07 27
20230727
2023 07 28
20230728
2023 08 04
20230804
{'in!'}
Downloading 20230804.zip
Deleted old ZIP: zips/20230804.zip
2023 08 10
20230810
2023 08 15
20230815
2023 08 17
20230817
2023 08 19
20230819
2023 08 22
20230822
2023 08 24
20230824
2023 08 25
20230825
2023 08 30
20230830
2023 08 31
20230831
2023 09 01
20230901
{'in!'}
Downloading 20230901.zip
Deleted old ZIP: zips/20230901.zip
2023 09 04
20230904
2023 09 06
20230906
2023 09 07
20230907
2023 09 08
20230908
2023 09 11
20230911
2023 09 12
20230912
2023 09 14
20230914
2023 09 21
20230921
2023 09 22
20230922
2023 09 28
20230928
2023 10 03
20231003
{'in!'}
Downloading 20231003.zip
Deleted old ZIP: zips/20231003.zip
2023 10 04
20231004
2023 10 11
20231011
2023 10 20
20231020
2023 10 27
20231027
2023 10 31
20231031
2023 11 02
20231102
{'in!'}
Downloading 20231102.zip
Deleted old ZIP: zips/20231102.zip
2023 11 08
20231108
2023 11 10
20231110
2023 11 14
20231114
2023 11 16
20231116
2023 11 25
20231125
2023 11 27
20231127
2023 11 28
20231128
2023 11 30
20231130
2023 12 02
20231202
{'in!'}
Downloading 20231202.zip
Deleted old ZIP: zips/20231202.zip
2023 12 03
20231203
2023 12 05
20231205
2023 12 08
20231208
2023 12 11
20231211
2023 12 15
20231215
2023 12 21
20231221
2023 12 26
20231226
2023 12 29
20231229
2024 01 01
20240101
{'in!'}
Downloading 20240101.zip
Deleted old ZIP: zips/20240101.zip
2024 01 02
20240102
2024 01 03
20240103
2024 01 05
20240105
2024 01 11
20240111
2024 01 24
20240124
2024 01 25
20240125
2024 01 27
20240127
2024 02 01
20240201
{'in!'}
Downloading 20240201.zip
Deleted old ZIP: zips/20240201.zip
2024 02 02
20240202
2024 02 05
20240205
2024 02 08
20240208
2024 02 09
20240209
2024 02 15
20240215
2024 02 20
20240220
2024 02 26
20240226
2024 02 28
20240228
2024 03 04
20240304
{'in!'}
Downloading 20240304.zip
Deleted old ZIP: zips/20240304.zip
2024 03 06
20240306
2024 03 07
20240307
2024 03 11
20240311
2024 03 13
20240313
2024 03 15
20240315
2024 03 19
20240319
2024 03 21
20240321
2024 03 27
20240327
2024 03 29
20240329
2024 04 02
20240402
{'in!'}
Downloading 20240402.zip
Deleted old ZIP: zips/20240402.zip
2024 04 05
20240405
2024 04 09
20240409
2024 04 12
20240412
2024 04 16
20240416
2024 04 18
20240418
2024 04 25
20240425
2024 05 03
20240503
{'in!'}
Downloading 20240503.zip
Deleted old ZIP: zips/20240503.zip
2024 05 07
20240507
2024 05 08
20240508
2024 05 14
20240514
2024 05 15
20240515
2024 05 17
20240517
2024 05 21
20240521
2024 05 27
20240527
2024 05 31
20240531
2024 06 07
20240607
{'in!'}
Downloading 20240607.zip
Deleted old ZIP: zips/20240607.zip
2024 06 11
20240611
2024 06 13
20240613
2024 06 25
20240625
2024 06 26
20240626
2024 06 27
20240627
2024 07 02
20240702
{'in!'}
Downloading 20240702.zip
Deleted old ZIP: zips/20240702.zip
2024 07 03
20240703
2024 07 09
20240709
2024 07 12
20240712
2024 07 16
20240716
2024 07 17
20240717
2024 07 19
20240719
2024 07 24
20240724
2024 07 26
20240726
2024 07 29
20240729
2024 08 02
20240802
{'in!'}
Downloading 20240802.zip
Deleted old ZIP: zips/20240802.zip
2024 08 07
20240807
2024 08 09
20240809
2024 08 16
20240816
2024 08 23
20240823
2024 08 28
20240828
2024 09 04
20240904
{'in!'}
Downloading 20240904.zip
Deleted old ZIP: zips/20240904.zip
2024 09 05
20240905
2024 09 16
20240916
2024 09 17
20240917
2024 09 20
20240920
2024 09 24
20240924
2024 09 25
20240925
2024 09 27
20240927
2024 09 30
20240930
2024 10 03
20241003
{'in!'}
Downloading 20241003.zip
Deleted old ZIP: zips/20241003.zip
2024 10 08
20241008
2024 10 11
20241011
2024 10 12
20241012
2024 10 14
20241014
2024 10 18
20241018
2024 10 21
20241021
2024 10 24
20241024
2024 10 25
20241025
2024 10 27
20241027
2024 10 31
20241031
2024 11 01
20241101
{'in!'}
Downloading 20241101.zip
Deleted old ZIP: zips/20241101.zip
2024 11 07
20241107
2024 11 12
20241112
2024 11 13
20241113
2024 11 15
20241115
2024 11 27
20241127
2024 11 28
20241128
2024 12 05
20241205
{'in!'}
Downloading 20241205.zip
Deleted old ZIP: zips/20241205.zip
2024 12 08
20241208
2024 12 16
20241216
2024 12 17
20241217
2024 12 24
20241224
2024 12 27
20241227
2025 01 02
20250102
{'in!'}
Downloading 20250102.zip
Deleted old ZIP: zips/20250102.zip
2025 01 06
20250106
2025 01 09
20250109
2025 01 10
20250110
2025 01 14
20250114
2025 01 20
20250120
2025 01 28
20250128
2025 01 29
20250129
2025 01 31
20250131
2025 02 06
20250206
{'in!'}
Downloading 20250206.zip
Deleted old ZIP: zips/20250206.zip
2025 02 07
20250207
2025 02 14
20250214
2025 02 18
20250218
2025 02 19
20250219
2025 02 25
20250225
2025 02 27
20250227
2025 03 04
20250304
{'in!'}
Downloading 20250304.zip
Deleted old ZIP: zips/20250304.zip
2025 03 05
20250305
2025 03 13
20250313
2025 03 17
20250317
2025 03 19
20250319
2025 03 20
20250320
2025 03 21
20250321
2025 03 25
20250325
2025 03 27
20250327
2025 03 31
20250331
2025 04 01
20250401
{'in!'}
Downloading 20250401.zip
Deleted old ZIP: zips/20250401.zip
2025 04 04
20250404
2025 04 09
20250409
2025 04 11
20250411
2025 04 17
20250417
2025 04 22
20250422
2025 04 24
20250424
2025 04 28
20250428
2025 05 01
20250501
{'in!'}
Downloading 20250501.zip
Deleted old ZIP: zips/20250501.zip
2025 05 06
20250506
2025 05 07
20250507
2025 05 08
20250508
2025 05 13
20250513
2025 05 15
20250515
2025 05 16
20250516
2025 05 21
20250521
2025 05 22
20250522
2025 05 26
20250526
2025 05 27
20250527
2025 05 28
20250528
2025 05 30
20250530
2025 06 05
20250605
{'in!'}
Downloading 20250605.zip
Deleted old ZIP: zips/20250605.zip
2025 06 06
20250606
2025 06 08
20250608
2025 06 09
20250609
2025 06 13
20250613
2025 06 18
20250618
2025 06 20
20250620
2025 06 23
20250623
2025 06 25
20250625
2025 06 26
20250626
2025 07 03
20250703
{'in!'}
Downloading 20250703.zip
Deleted old ZIP: zips/20250703.zip
2025 07 09
20250709
2025 07 14
20250714
2025 07 15
20250715
2025 07 18
20250718
2025 07 21
20250721
2025 07 23
20250723
2025 07 24
20250724
2025 07 28
20250728
2025 07 29
20250729
2025 07 30
20250730
2025 07 31
20250731
2025 08 05
20250805
{'in!'}
Downloading 20250805.zip
Deleted old ZIP: zips/20250805.zip
2025 08 06
20250806
2025 08 07
20250807
2025 08 11
20250811
2025 08 13
20250813
2025 08 14
20250814
2025 08 18
20250818
2025 08 19
20250819
2025 08 20
20250820
2025 08 22
20250822
2025 08 27
20250827
2025 08 28
20250828
2025 09 01
20250901
{'in!'}
Downloading 20250901.zip
Deleted old ZIP: zips/20250901.zip
2025 09 04
20250904
2025 09 09
20250909
2025 09 12
20250912
2025 09 15
20250915
2025 09 17
20250917
2025 09 22
20250922
2025 09 23
20250923
2025 09 25
20250925
2025 10 07
20251007
{'in!'}
Downloading 20251007.zip
Deleted old ZIP: zips/20251007.zip
2025 10 14
20251014
2025 10 21
20251021
2025 10 28
20251028
2025 10 30
20251030
2025 10 31
20251031
2025 11 05
20251105
{'in!'}
Downloading 20251105.zip
Deleted old ZIP: zips/20251105.zip
2025 11 07
20251107
2025 11 12
20251112
2025 11 14
20251114
2025 11 18
20251118
2025 11 19
20251119
2025 11 24
20251124
2025 11 27
20251127
2025 12 02
20251202
{'in!'}
Downloading 20251202.zip
Deleted old ZIP: zips/20251202.zip

In [ ]:
# to download all the current stop time files in the stop_times directory
output_path = "monthly_stop_times.csv"
first = True
dir = glob.glob(f'/Users/sierrawelsch/CS4100_Final/src/preprocessing/stop_times/*.txt')
df_list = []
use_cols = ["trip_id", "arrival_time", "departure_time", "stop_id", "stop_sequence"]
for time_csv_file in dir:
    file_name = os.path.basename(time_csv_file)
    time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

    date_str = os.path.basename(time_csv_file).replace(".txt", "")
    date_str = date_str[:6]
    print(date_str)
    time_csv_file_df["stops_month"] = pd.to_datetime(date_str, format="%Y%m")
    
    mod_df = time_csv_file_df.dropna()
    
    # export all of the stop time entries to one csv
    mod_df.to_csv(output_path, mode='a', header=first, index=False)
    first = False

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202503

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202311

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202507

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202505

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202401

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202211

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202308

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202407

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202403

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202501

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202208

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202405

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202309

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202504

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202210

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202312

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202406

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202502

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202402

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202310

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202212

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202404

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202506

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202209

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202411

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202508

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202303

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202305

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202511

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202205

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202207

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202408

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202307

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202201

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202301

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202203

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202510

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202204

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202410

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202202

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202206

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202302

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202306

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202512

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202304

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202409

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202509

/var/folders/z7/152736054bv0sl_wm9ygspfr0000gn/T/ipykernel_38036/130653243.py:9: DtypeWarning: Columns (0: trip_id, 1: stop_id) have mixed types. Specify dtype option on import or set low_memory=False.
  time_csv_file_df = pd.read_csv(time_csv_file, usecols=use_cols)

202412